def write_resultso(t, meanX, meanY, meanZ, m2X, m2Y, m2Z, m3X, m3Y, m3Z, m4X, m4Y, m4Z):

  finalResultso = open("Finalo.ods", "w")

  finalResultso.write("Time:")
  finalResultso.write(" ")
  finalResultso.write("MeanX:")
  finalResultso.write(" ")
  finalResultso.write("MeanY:")
  finalResultso.write(" ")
  finalResultso.write("MeanZ:")
  finalResultso.write(" ")
  finalResultso.write("Moment2X:")
  finalResultso.write(" ")
  finalResultso.write("Moment2Y:")
  finalResultso.write(" ")
  finalResultso.write("Moment2Z:")
  finalResultso.write(" ")
  finalResultso.write("Moment3X:")
  finalResultso.write(" ")
  finalResultso.write("Moment3Y:")
  finalResultso.write(" ")
  finalResultso.write("Moment3Z:")
  finalResultso.write(" ")
  finalResultso.write("Moment4X:")
  finalResultso.write(" ")
  finalResultso.write("Moment4Y:")
  finalResultso.write(" ")
  finalResultso.write("Moment4Z:")
  finalResultso.write("\n")
  
  i = 0
  while i < 100:
  
    finalResultso.write(str(t[i]))
    finalResultso.write(" ")
    finalResultso.write(str(meanX[i]))
    finalResultso.write(" ")
    finalResultso.write(str(meanY[i]))
    finalResultso.write(" ")
    finalResultso.write(str(meanZ[i]))
    finalResultso.write(" ")
    finalResultso.write(str(m2X[i]))
    finalResultso.write(" ")
    finalResultso.write(str(m2Y[i]))
    finalResultso.write(" ")
    finalResultso.write(str(m2Z[i]))
    finalResultso.write(" ")
    finalResultso.write(str(m3X[i]))
    finalResultso.write(" ")
    finalResultso.write(str(m3Y[i]))
    finalResultso.write(" ")
    finalResultso.write(str(m3Z[i]))
    finalResultso.write(" ")
    finalResultso.write(str(m4X[i]))
    finalResultso.write(" ")
    finalResultso.write(str(m4Y[i]))
    finalResultso.write(" ")
    finalResultso.write(str(m4Z[i]))
    finalResultso.write("\n")

    i = i + 1

  finalResultso.close()

